global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'collab-chat'
    metrics_path: '/collab-chat/actuator/prometheus'
    static_configs:
      - targets: ['collabchat-app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'collab-chat'
